### ISSUE TITLE
HELP ME Sir

### ISSUE THREAD

**Issue by shayanshaiz007** [pralinkhaira/Insta-Cypher#13]
Sir Please Help me 
When I Install TOR 
fatal unable to access  'https://github.com/pralinkhaira/Insta-Cypher' : could not resolve host :gtihub 

What is solve of this problem Sir
Please Help me

**Comment by prathamlal20** [comment]
Don't clone while using root.
Clone while in terminal only

**Comment by pralinkhaira** [comment]
> Don't clone while using root. Clone while in terminal only

Thanks for the help buddy! I'm kinda busy right now, so i cant even reply to all these, Thanks :)

**Comment by pralinkhaira** [comment]
Also

Instagram limited the password input or you can say the correct password entering (brute force) requests per user, to protect it from bot attacks, so I'll update the script when I'll be free.
