### ISSUE TITLE
Long Time To Run

### ISSUE THREAD

**Issue by DoDoBird-Extinct** [pralinkhaira/Insta-Cypher#14]
Hi, when I run the program, it seems to continue for a long time and then it crashes. I have tried saving the sessions to start them up again but dont know how to reopen the same session. I have also runned it multiple times and have yet to get access to the actual account.

**Comment by pralinkhaira** [comment]
Instagram limited the password input or you can say the correct password entering (brute force) requests per user, to protect it from bot attacks, so I'll update the script when I'll be free.
