### ISSUE TITLE
I'm learning how to use the functions of Kali Linux I want to learn at home even due to lack of time and conditions, can you explain to me how I can install the code for correct operation

### ISSUE THREAD

**Issue by gugaz3007** [pralinkhaira/Insta-Cypher#15]
I'm learning how to use the functions of Kali Linux I want to learn at home even due to lack of time and conditions, can you explain to me how I can install the code for correct operation

**Comment by pralinkhaira** [comment]
Instagram limited the password input or you can say the correct password entering (brute force) requests per user, to protect it from bot attacks, so I'll update the script when I'll be free.
