### ISSUE TITLE
Cant find the password

### ISSUE THREAD

**Issue by VILLA329** [pralinkhaira/Insta-Cypher#17]
I run the code but the password is not there, how can i found it?

**Comment by ry609** [comment]
[_anonymous_frrrr](https://www.instagram.com/_anonymous_frrrr/#)

**Comment by exoticher10** [comment]
i want to know somebody instagram password

**Comment by exoticher10** [comment]
can anybody help me?

**Comment by pralinkhaira** [comment]
> I run the code but the password is not there, how can i found it?

try adding more possible passwords to brute force list :)
