### ISSUE TITLE
how do I know if it is running correctly?

### ISSUE THREAD

**Issue by Feliciawalter** [pralinkhaira/Insta-Cypher#19]
I have added my passwords in the combination is it cracking it.

**Comment by zainab689** [comment]
Hy do you know how to crack insta password ??

**Comment by shayanshaiz007** [comment]
I don't know dude! if you know so please tell me 

Thankss..

**Comment by zainab689** [comment]
Yeah okay😃

**Comment by shayanshaiz007** [comment]
Thaanks :))

**Comment by shayanshaiz007** [comment]
@zainab689 do u ha*k any account ?

**Comment by zainab689** [comment]
I never hack any account 😅

**Comment by shayanshaiz007** [comment]
So, @zainab689 still u r found the hack any account ? :)?

**Comment by zainab689** [comment]
??

**Comment by zainab689** [comment]
Yes

**Comment by shayanshaiz007** [comment]
if u found then inform me please... @zainab689

**Comment by zainab689** [comment]
Yes, I did.

**Comment by shayanshaiz007** [comment]
What u did ? @zainab689

**Comment by zainab689** [comment]
Nothing much, you?

**Comment by shayanshaiz007** [comment]
Still nothing

**Comment by zainab689** [comment]
That's weird.

**Comment by shayanshaiz007** [comment]
Yeah! What are you doing?

**Comment by zainab689** [comment]
NOthing 😄

**Comment by zainab689** [comment]
＼（＠￣∇￣＠）／😆😊

**Comment by shayanshaiz007** [comment]
@zainab689 , Study wagera nh krti ho?

**Comment by zainab689** [comment]
KRti hu study abhi hi punjab university mein entry test ky liye apply kiya
hai 😀

**Comment by shayanshaiz007** [comment]
Oh Great !

**Comment by zainab689** [comment]
Glad to hear it!

**Comment by zainab689** [comment]
≧◉◡◉≦

**Comment by shayanshaiz007** [comment]
:-)
