### ISSUE TITLE
Script fails to indicate correct password.

### ISSUE THREAD

**Issue by 3GRAVES** [pralinkhaira/Insta-Cypher#25]
Script runs smoothly but will glaze over a correct pw without returning a positive indication that it has received a match. Tor connection is solid. Running on kali. Any help appreciated, my bash script knowledge is not the best. :)

(FYI: I created a .txt containing the correct password for the account myself so I know that it is a match).

**Comment by pralinkhaira** [comment]
Instagram limited the password brute force requests per user, so I'll update the script when I'll be free.

**Comment by slr101** [comment]
Bro I'm also getting the same problem

**Comment by pralinkhaira** [comment]
> Bro I'm also getting the same problem

[Problem Solution Here](https://github.com/pralinkhaira/Insta-Cypher?tab=readme-ov-file#note)
