### ISSUE TITLE
request

### ISSUE THREAD

**Issue by Davidasdas** [pralinkhaira/Insta-Cypher#3]
Hi,
I want guys to help delate or hack an Instagram account, because that person he insulted me , defamed me an threatened me in public, he use my name on screen shot in public, I reported him on Instagram and meta, but need more than 45 people to report him and than insta can delate his account. so could you please help me on that,
Thank you

**Comment by pralinkhaira** [comment]
Not a proper place for this, you can try uploading a story, letting you followers know to report that account.
