### ISSUE TITLE
> Para todo tipos de fotos[](url)

### ISSUE THREAD

**Issue by Maniel241** [pralinkhaira/Insta-Cypher#34]
> Para todo tipos de fotos[](url)
`

_Originally posted by @Maniel241 in https://github.com/pralinkhaira/Insta-Cypher/issues/33#issuecomment-2327600915_

**Comment by pralinkhaira** [comment]
[Problem Solution Here](https://github.com/pralinkhaira/Insta-Cypher?tab=readme-ov-file#note)
