### ISSUE TITLE
Fake 

### ISSUE THREAD

**Issue by Mit75587** [pralinkhaira/Insta-Cypher#35]
Not really works it is only showing trying password but it is not working. Please solve my issue tor is working perfectly

**Comment by pralinkhaira** [comment]
[Problem Solution Here](https://github.com/pralinkhaira/Insta-Cypher?tab=readme-ov-file#note)

**Comment by Mit75587** [comment]
Har bar yahi pe aake atak aaraha hai jabki mere password is list hai hai
testing me bhi pass nahi ho raha hai

**Comment by pralinkhaira** [comment]
Bhai yaar instagram ne change kiye apne security measures, and uske hisab se i too have to change the script, but i can't as i'm just busy with some of my exams and final year projects!
Hope you understand!

**Comment by Mit75587** [comment]
Ok, no problem.

**Comment by Mit75587** [comment]
Instagram pe request to le lena
