### ISSUE TITLE
i tested with the right password nothing happened

### ISSUE THREAD

**Issue by Zxr4n** [pralinkhaira/Insta-Cypher#40]
the script works fine but i tested on my personnal account with the right password in the list and nothing happened

**Comment by pralinkhaira** [comment]
For god's sake just open your eyes and carefully read the full [README.md](https://github.com/pralinkhaira/Insta-Cypher/blob/main/README.md) before opening any unnecessary issues to just spam this repo

[Read This](https://github.com/pralinkhaira/Insta-Cypher?tab=readme-ov-file#note)
