### ISSUE TITLE
Instagram 

### ISSUE THREAD

**Issue by Shoebpathan1200** [pralinkhaira/Insta-Cypher#43]
https://help.instagram.com/345310197245685/?helpref=uf_share

**Comment by Shoebpathan1200** [comment]
This account password

**Comment by Shoebpathan1200** [comment]
1. 1235y #40

**Comment by duda650** [comment]
I would like help

**Comment by pralinkhaira** [comment]
> 1. 1235y [i tested with the right password nothing happened #40](https://github.com/pralinkhaira/Insta-Cypher/issues/40)

IDK if you are acting dumb or actually are dumb :)

![image](https://github.com/user-attachments/assets/3a9f04ba-2118-44c2-ac6b-c1b1a6fe671c)
