### ISSUE TITLE
Feedback and Suggestion

### ISSUE THREAD

**Issue by NickDeBeenSAE** [pralinkhaira/Insta-Cypher#45]
I would recommend a feature that uses every character on any keyboard during the brute-force attack, but ensure that the correctly brute-forced character is kept while the other characters are still being brute-forced.

**Comment by pralinkhaira** [comment]
Great buddy, and thanks for the suggestion. I'll implement this along with updating the script as soon as possible :)

**Comment by NickDeBeenSAE** [comment]
Recommendation:

Self updater for the script.

This allows the script to automatically update when there are any changes made in its code.

**Comment by pralinkhaira** [comment]
Great, I'll consider this too!
