### ISSUE TITLE
pid 96293 is not a child of this shell

### ISSUE THREAD

**Issue by waavvv** [pralinkhaira/Insta-Cypher#5]
./insta.sh: line 156: wait: pid 96293 is not a child of this shell
<img width="1440" alt="Screenshot 2024-05-26 at 21 28 48" src="https://github.com/pralinkhaira/Insta-Cypher/assets/112268440/23442b9f-78be-4411-b3df-13c893365c20">

**Comment by pralinkhaira** [comment]
Are you running this on linux terminal?

**Comment by VILLA329** [comment]
it gaves me the same error, I am runing it in a mac

**Comment by pralinkhaira** [comment]
> it gaves me the same error, I am runing it in a mac

Mac wont help bud, get a Linux environment or a virtual box with Linux installed!
