### ISSUE TITLE
Bro i added my insta password and used my insta id to check  but not working bro why?

### ISSUE THREAD

**Issue by vishnu0010** [pralinkhaira/Insta-Cypher#6]

**Comment by pralinkhaira** [comment]
Explain in detail, with some screenshots and videos even logs if possible
(Dont share your insta password tho)

**Comment by cathub-blip** [comment]
im unable to find instapass tho can anyone help i can provide user name

**Comment by pralinkhaira** [comment]
> im unable to find instapass tho can anyone help i can provide user name

Instagram limited the password input or you can say the correct password entering (brute force) requests per user, to protect it from bot attacks, so I'll update the script when I'll be free.
