### ISSUE TITLE
In need of help please 

### ISSUE THREAD

**Issue by Needinghelpplease** [pralinkhaira/Insta-Cypher#9]
Complete noob here. I have no idea how to run this in root. I tried “sudo -i” and I can get the terminal in root but it’s not letting me open the insta cypher in root. 
![IMG_7505](https://github.com/pralinkhaira/Insta-Cypher/assets/171518336/1b637520-1a94-42ee-b097-9ac5a8ff3513)

**Comment by pralinkhaira** [comment]
Open the terminal as root!

**Comment by Needinghelpplease** [comment]
Yes but how ? When I right click the file it’s only asking to open the
terminal. Not as root.

**Comment by TioRandomv** [comment]
were you able to solve it?

**Comment by Needinghelpplease** [comment]
No lol

**Comment by TioRandomv** [comment]
*cry*

**Comment by pralinkhaira** [comment]
> Yes but how ? When I right click the file it’s only asking to open the terminal. Not as root.

Press Ctrl + Alt + T to open a terminal window. Type “sudo” before the rest of your command to run it as root.

**Comment by JPawan-08** [comment]
I tried but it said tor is not installed. Aborting 
But tor was already downloaded

**Comment by TioRandomv** [comment]
I did that and I get errors, then it keeps asking me to start as root
T_T help pls

**Comment by TioRandomv** [comment]
I can! buth now it says: I require curl buth its not installed. aborting

**Comment by 3GRAVES** [comment]
Type tor in a seperate terminal window and wait for it to 100% bootstrap, then run “sudo ./insta.sh”. Type your sudo password and it should run.

**Comment by pralinkhaira** [comment]
Instagram limited the password input or you can say the correct password entering (brute force) requests per user, to protect it from bot attacks, so I'll update the script when I'll be free.
